### ISSUE TITLE
Fix: replace 404 URLs in the source

### ISSUE THREAD

**Issue by yo1995** [Esri/arcgis-runtime-toolkit-ios#144]
Spot 1 👇  when running another task.

https://github.com/Esri/arcgis-runtime-toolkit-ios/blob/b88e8ceceeae75d0fd85ea12256a15dc332d75c1/Sources/ArcGISToolkit/JobManager.swift#L220

One can use `grep -nr 'ios/latest' arcgis-runtime-toolkit-ios` to search for the old pattern of URLs in the source.

**Comment by mhdostal** [comment]
@yo1995 Thank you for catching this!  This can be fixed for the Update 11 release.
