### ISSUE TITLE
Build errors with Xcode 13 Beta 3

### ISSUE THREAD

**Issue by saratchandrakarumuri** [Esri/arcgis-runtime-toolkit-ios#150]
With the latest beta of Xcode 13, while building sampleViewer, we get this following error with the toolkit `Extensions.swift`  and `MeasureToolbar.swift` files

`'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.`

![2021-07-20 at 3 51 PM](https://user-images.githubusercontent.com/8692125/126405227-b38f6ac9-1e25-4e30-a3b0-981e9a558634.png)

**Comment by mhdostal** [comment]
Thanks @saratchandrakarumuri .  Looks like the error is new with Beta 3.  Some links to help myself with fixing this:

https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/20

https://bugs.swift.org/browse/SR-14944
