### ISSUE TITLE
PopupController Example: initial size of added attachment images in incorrect

### ISSUE THREAD

**Issue by mhdostal** [Esri/arcgis-runtime-toolkit-ios#156]
In the PopupController Example, adding an image attachment (via "Choose From Library") to either a new or existing feature results in the size displaying as "-1.0 bytes".  Saving the feature and reselecting it causes the attachment sizes to display correctly.

Adding an attachment directly from a new image (via "Take Photo or Video"), displays the correct size.

Steps to reproduce:
- In the PopupController example, tap an existing feature
- Tap the "Attached" segment/tab to view attachments and then start editing via the "Edit" button
- Tap "Add Attachment" and select "Choose From Library" 
- Select an image from the Library and give it the default name.
- Notice the size says: "-1.0 bytes".

After adding attachments (note that "Photo3.jpg" was a new image from the camera and displays the correct size):

![image](https://user-images.githubusercontent.com/3998072/130534763-8cff3b70-5ee6-4b01-8a5d-dfd9d3bbe171.png)

After saving the feature, going back to the map, and re-selecting the same feature results in correct sizes:

![image](https://user-images.githubusercontent.com/3998072/130534838-da141904-c4f4-4272-b77b-4b35c9b26c26.png)

The initial sizes should appear correctly immediately after adding the attachment.

Built using Xcode 12.5 and v100.12 of the ArcGIS Runtime SDK.
Run on an iPhone 8 with iOS v14.7.1
Also occurs in the Simulator (iPad Pro 9.7" iOS 14.5)

**Comment by rolson** [comment]
This issue is more than likely in the runtime I would've thought.

**Comment by mhdostal** [comment]
Fixed in the iOS SDK.
