### ISSUE TITLE
Remove usage of BasemapType and Basemap static initializers in favor of BasemapStyles

### ISSUE THREAD

**Issue by mhdostal** [Esri/arcgis-runtime-toolkit-ios#165]
The following methods have been deprecated in the ArcGIS Runtime SDK for iOS.  They need to be replaced in all code and documentation by the appropriate "basemap styles" initializers.

`AGSMap`

```swift
- (instancetype)initWithBasemapType:(AGSBasemapType)basemapType
                           latitude:(double)latitude
                          longitude:(double)longitude
                      levelOfDetail:(NSInteger)levelOfDetail __deprecated_msg("Use 'AGSMap#initWithBasemapStyle:'");
+ (instancetype)mapWithBasemapType:(AGSBasemapType)basemapType
                          latitude:(double)latitude
                         longitude:(double)longitude
                     levelOfDetail:(NSInteger)levelOfDetail __deprecated_msg("Use 'AGSMap#mapWithBasemapStyle:'");
```

`AGSScene`

```swift
- (instancetype)initWithBasemapType:(AGSBasemapType)basemapType __deprecated_msg("Use 'AGSScene#initWithBasemapStyle:'.");
+ (instancetype)sceneWithBasemapType:(AGSBasemapType)basemapType __deprecated_msg("Use 'AGSScene#sceneWithBasemapStyle:'.");
```

`AGSBasemap`

- The `AGSBasemapType` enumeration and all static `AGSBasemap` initializers based on ArcGIS Online types.

**Comment by maryharvey** [comment]
@mhdostal Do these styles require that the user supplies their own API Key? If so, should this information go into the Examples ReadMe Instructions?

**Comment by mhdostal** [comment]
> Do these styles require that the user supplies their own API Key? If so, should this information go into the Examples ReadMe Instructions?

@maryharvey Yes.  @dfeinzimer has opened [this](https://github.com/Esri/arcgis-runtime-toolkit-ios/pull/169) PR to address the repo doc.
