### ISSUE TITLE
Possible to use with static framework of ArcGIS Runtime SDK for iOS?

### ISSUE THREAD

**Issue by yozaw** [Esri/arcgis-runtime-toolkit-ios#17]
My project uses static ArcGIS.framework.
Drag and Drop the ArcGISToolkit.xcodeproj file into my project.
An running error occurred.

dyld: Library not loaded: @rpath/ArcGIS.framework/ArcGIS
  Referenced from: /Users/apps/Library/Developer/Xcode/DerivedData/ArcGISToolkitExamples-ghoiwslxqdkgkqcguihehpstocng/Build/Products/Debug-iphonesimulator/ArcGISToolkit.framework/ArcGISToolkit
  Reason: image not found

**Comment by amiscorp** [comment]
how did u fixed this issue?Me also same issue is facing
