### ISSUE TITLE
LegendViewController displays imagery and other metadata

### ISSUE THREAD

**Issue by timmons-jamese** [Esri/arcgis-runtime-toolkit-ios#173]
When using the LegendViewController with an AGOL web map that uses the World Imagery Hybrid basemap, the legend displays imagery and other metadata that does not appear in the AGOL legend.  See attached screenshots and sample project.

Is there a way to hide this information without writing a custom legend view?

![AGOL Legend](https://user-images.githubusercontent.com/104579010/165791015-c08a3c56-3bd9-4e72-9608-6606d62c42cb.png)
![Mobile Legend 1](https://user-images.githubusercontent.com/104579010/165791017-758961bb-c900-4682-b7c1-37f9459e74ca.png)
![Mobile Legend 2](https://user-images.githubusercontent.com/104579010/165791018-6f8c9369-37e8-4f8b-9e74-9ce440f1eb60.png)
![Mobile Legend 3](https://user-images.githubusercontent.com/104579010/165791021-23c52380-8be2-42db-b501-28b4ad8782fb.png)
[Timmons-AGSLegendExample.zip](https://github.com/Esri/arcgis-runtime-toolkit-ios/files/8584244/Timmons-AGSLegendExample.zip)

**Comment by mhdostal** [comment]
@timmons-jamese - Thank you for your question and for using the Toolkit!  The answer is, yes, you can hide the basemap layers and data and prevent if from being shown in the legend.

By default, basemap information is displayed in the legend.  An `AGSBasemap` has both "base layers" and "referenceLayers" arrays.  Each element in those arrays are an `AGSLayer`, which implements the `AGSLayerContent` protocol.  That protocol has a `showInLegend` property.  So hiding the basemap in the legend is simply a matter of looping through all the base and reference layers and setting the `showInLegend` property to false:
