### ISSUE TITLE
Installing arcgis-runtime-toolkit-ios via Cocoapods does not reflect newest toolkit items

### ISSUE THREAD

**Issue by esreli** [Esri/arcgis-runtime-toolkit-ios#24]
adding:

`pod 'ArcGIS-Runtime-Toolkit-iOS'`

to my Podfile does not download the latest toolkit release but instead the `(100.1.0)` version.

Additionally, the Cocoapods pod documentation reflect documentation as of 100.1.0:
http://cocoadocs.org/docsets/ArcGIS-Runtime-Toolkit-iOS/100.1.0/

Also, a user will not be able to download the latest `ArcGIS-Runtime-SDK-iOS` cocoapod version `100.2.1` because this cocoapod depends on a specific minor version:
```
    ArcGIS-Runtime-Toolkit-iOS was resolved to 100.1.0, which depends on
      ArcGIS-Runtime-SDK-iOS (~> 100.1.0)
```

**Comment by mhdostal** [comment]
Some of the new components were just merged into master this week and the TimeSlider is under review.  The repo hasn't been tagged for 100.2.x yet, so the only tag is "100.1.0" (I'm not sure if that's what's causing the CocoaPods issue); I'm assuming that will happen when we get everything in that we want for the next release.

@dg0yal, @rolson - Do we have a plan for what components will go into the Toolkit before the next "release"?  I'm assuming at that point a new tag would be added an the Cocoapods stuff set up to work with that.

**Comment by dg0yal** [comment]
@mhdostal The timeslider will take a bit of time but we can proceed with creating a new release based off the new components that were added this week. I will try to do this by the end of the week. @rolson said we might have another minor PR coming through, let me know when that's in. I'll wait for it. 

@esreli You're right. The way the dependency has been specified it will restrict itself to only patches on top of 100.1 (for eg 100.1.1, 100.1.2, ... 100.1.x) of the sdk. Wont automatically upgrade to a new minor version such as 100.2

**Comment by dg0yal** [comment]
version 100.2.0 of the toolkit is now tagged and officially available through cocoapods. Cocoapods will pull the latest 100.2.x version of the SDK as a dependency for it
