### ISSUE TITLE
Table of Contents in ArcGIS Runtime Toolkit

### ISSUE THREAD

**Issue by ShiminCai** [Esri/arcgis-runtime-toolkit-ios#32]
We would like to have a TOC sample using the SDK 100.2.1 that could:
1. turn layers on/off including operational layers, basemaplayers, tile package layers and runtime database layers, etc.
2. layers can be expanded to show layer legends/feature templates.
3. Our current TOC is built based on the previous TOC sample in the SDK 10.2.x. If a feature template from a feature service or an offline database is tapped, it puts the map into editing mode and then feature geometry can be sketched and new feature can be created and saved.

**Comment by mhdostal** [comment]
@ShiminCai - In case you're still interested, there is an implementation of a customizable Legend/TOC in Esri's DataCollection Open Source App for iOS.  You can find the repo [here](https://github.com/esri/data-collection-ios).  The main class is the `LayerContentsViewController` [here](https://github.com/Esri/data-collection-ios/blob/master/data-collection/data-collection/View%20Controllers/Layer%20Contents%20View%20Controllers/LayerContentsViewController.swift).

A screenshot of it in the Data Collection app (taken from the Data Collection docs):

![image](https://user-images.githubusercontent.com/3998072/90440416-d0c03980-e09c-11ea-9818-7948487e695c.png)

**Comment by ShiminCai** [comment]
Many thanks Mark. We found the same code one year ago and have used the code in our apps. Cheers, Shimin
