### ISSUE TITLE
JobManager sample not taking advantage of background fetch

### ISSUE THREAD

**Issue by rolson** [Esri/arcgis-runtime-toolkit-ios#45]
We need to augment the JobManager sample to take advantage of background fetch. It was meant to do that, however I believe the code was lost in a merge at some point. See documentation here:

```
 For supporting background fetch you can forward the call from your AppDelegate's
 `func application(_ application: UIApplication, performFetchWithCompletionHandler completionHandler: @escaping` 
 function, to the same function in this class.
```

**Comment by nixta** [comment]
It would seem better to use a Background Task to be more deterministic about this. Background fetch is opportunistic and changes in frequency at least partially based off how often you return `.noData` in the fetch ping. Background Task is time bound but currently (iOS 12) [seems to be about 10 minutes](https://stackoverflow.com/a/28283577/1416253).

CC @eito

**Comment by rolson** [comment]
This issue can be closed, I fixed it at Update 5.

> It would seem better to use a Background Task to be more deterministic about this. Background fetch is opportunistic and changes in frequency at least partially based off how often you return .noData in the fetch ping. Background Task is time bound but currently (iOS 12) seems to be about 10 minutes.

I don't know that the user couldn't do both. They can create a background task when kicking off the job for example. If you want the toolkit sample to do that please create a separate issue. 

Thanks!
