### ISSUE TITLE
Missing CompassIcon

### ISSUE THREAD

**Issue by mdvisla** [Esri/arcgis-runtime-toolkit-ios#55]
CompassIcon is missing and as a result, nothing is being displayed on a screen. It's a little frustrating to find out the reason for that behaviour. Can anyone add a sample compass icon?

**Comment by mhdostal** [comment]
If you open up the `ArcGISToolkitExamples.xcodeproj` file, run the app from Xcode, and select the `Compass` example, you can see that the compass does appear.  Note that there is a property on the `Compass` toolkit component, `autoHide`, which will hide the compass when the map rotation is 0, so you will need to rotate the map to see the compass.

The compass icons are in the `Assets.xcassets` file in the ArcGISToolkit project, so if you are not using the `ArcGISToolkit.xcodeproj` project and instead pulling the Compass.swift file in manually, you will also need to include the compass icons in your project.

**Comment by mdvisla** [comment]
Oh, I didn't see it in .xcassets

Thanks
