### ISSUE TITLE
Add moving graphics

### ISSUE THREAD

**Issue by nafeesahmedrao** [Esri/arcgis-runtime-toolkit-ios#56]
I need to show a graphic moving between two coordinates, please suggest me how to implement it.

**Comment by mhdostal** [comment]
Take a look at [this](https://community.esri.com/thread/200011-pulse-animation-in-marker-same-like-current-location#comment-708876) GeoNet post.  It shows how to animate the size of a graphic, but you could easily adapt the code to change the graphic's geometry.

In the future, you can post general questions on the "ArcGIS Runtime SDK for iOS" GeoNet forum [here](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-ios).

**Comment by esreli** [comment]
Piggy-backing off of @mhdostal, i'll also point you in the direction of an open source tool written by @nixta that solves a problem similar to yours. 

https://github.com/nixta/iOS-runtime-animations
